/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32h743xx.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void init_GPIO(void);
void init_syscfg(void);
void init_interrupt(void);

int main(void) {

	int i;

	init_GPIO();
	init_syscfg();
	init_interrupt();

	/* Loop forever */
	while (1) {

//		GPIOB->ODR |= (0x1 << 0);
//		GPIOB->ODR |= (0x1 << 14);
//		GPIOE->ODR |= (0x1 << 1);
//
//		for (i = 0; i < 1000000; i++)
//			;
//
//		GPIOB->ODR = ~(GPIOB->ODR);
//		GPIOE->ODR = ~(GPIOE->ODR);
//
//		for (i = 0; i < 1000000; i++)
//			;

	}

	return 0;
}

void init_GPIO(void) {

	int i;

	RCC->AHB4ENR |= (0x1 << 1); // clock configuration for GPIO port B
	RCC->AHB4ENR |= (0x1 << 4); // clock configuration for GPIO port E
	RCC->AHB4ENR |= (0x1 << 2); // clock configuration for GPIO port C

	GPIOB->MODER &= ~(0x3 << 0); // set up mode register for PB0
	GPIOB->MODER |= (0x1 << 0);

	GPIOB->MODER &= ~(0x3 << 28); // set up mode register for PB14
	GPIOB->MODER |= (0x1 << 28);

	GPIOE->MODER &= ~(0x3 << 2); // set up mode register for PE1
	GPIOE->MODER |= (0x1 << 2);

	GPIOC->MODER &= ~(0x3 << 26); // set up mode register for PC13

	GPIOB->PUPDR &= ~(0x3 << 0); // set up pull_up pull_down register for PB0
	GPIOB->PUPDR |= (0x2 << 0);

	GPIOB->PUPDR &= ~(0x3 << 28); // set up pull_up pull_down register for PB14
	GPIOB->PUPDR |= (0x2 << 28);

	GPIOE->PUPDR &= ~(0x3 << 2); // set up pull_up pull_down register for PE1
	GPIOE->PUPDR |= (0x2 << 2);

	GPIOC->PUPDR &= ~(0x3 << 26); // set up pull_up pull_down register for PC13
	GPIOC->PUPDR |= (0x2 << 26);

}

void init_syscfg(void) {

	RCC->APB4ENR |= (0x1 << 1);

}

void init_interrupt(void) {

	SYSCFG->EXTICR[3] &= ~(0xf << 4);
	SYSCFG->EXTICR[3] |= (0x2 << 4);

	EXTI->IMR1 |= (0x1 << 13); // Interrupt request from line  (x=13) is not masked.

	EXTI->RTSR1 |= (0x1 << 13); // 1: Rising trigger enabled (for Event and Interrupt) for input line

// interrupt number (IRQ position ) : 40
//					NVIC->ISER[1] |= (0x1 << 40);
	NVIC_EnableIRQ(40);

}

void EXTI15_10_IRQHandler(void) {

	EXTI->PR1 |= (0x1 << 13);
//	GPIOB->ODR |= (0x1 << 0);
	GPIOB->ODR = ~GPIOB->ODR;
	GPIOE->ODR = ~GPIOE->ODR;

}

